name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Código Limpio (Flake8 + Tests)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Crear entorno virtual e instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip wheel
          pip install "setuptools<58.0.0"
          pip install -r requirements.txt
          pip install flake8 pytest boto3 beautifulsoup4 "moto<5.0" awscli zappa

      - name: Configurar PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Ejecutar Flake8
        run: |
          source venv/bin/activate
          flake8 .

      - name: Ejecutar pruebas con pytest
        run: |
          source venv/bin/activate
          pytest -v

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Listar buckets en S3
        run: |
          source venv/bin/activate
          aws s3 ls
