name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: C贸digo Limpio (Flake8)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install flake8

      #- name: Revisar calidad del c贸digo con Flake8
       # run: flake8 --max-line-length=180

  test:
    #name: Pruebas Unitarias (pytest)
    #runs-on: ubuntu-latest
    #needs: lint
    #steps:
      #- name: Checkout del c贸digo
      #  uses: actions/checkout@v3

      #- name: Configurar Python
       # uses: actions/setup-python@v3
        #with:
         # python-version: '3.9'

      - name: Instalar dependencias y configurar entorno virtual
        run: |
          python -m venv venv
          venv/bin/pip install --upgrade pip wheel
          venv/bin/pip install "setuptools<58.0.0"
          venv/bin/pip install -r requirements.txt
          venv/bin/pip install pytest boto3 beautifulsoup4 "moto<5.0" awscli zappa

      - name: Configurar PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: list buckets
        run: aws s3 ls

